dist: trusty
deploy:
  #provider: pages
  #skip_cleanup: true
  #github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: main
jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DockerPass" | docker login -u "$DockerID" --password-stdin
      - docker build -t travis-ci-build-stages-demo .
      - docker images
      - docker tag travis-ci-build-stages-demo $DockerID/travis-ci-build-stages-demo
      - docker push $DockerID/travis-ci-build-stages-demo
