pool:
  vmImage: 'Ubuntu 16.04'

variables:
# this group variable contains variables group that has acrName, acruser and password in it that we set in pipeline library.
# define three more variables acrName, dockerId and dockerPassword in the build pipeline in UI
  - group: acr01
# imageName variable is just a stangalone variable that is being created and used in this file only.
  - name: imageName
    value: 'angularapp:$(Build.BuildId)'
  
steps:
- script: docker build -f Dockerfile -t $(acrName).azurecr.io/$(imageName) .
  displayName: 'docker build'
# acr docker ID and passwd is located in azure container registry "Access Keys Setting"
- script: docker login -u $(dockerId) -p $(dockerPassword) $(acrName).azurecr.io
  displayName: 'docker login'

- script: docker push $(acrName).azurecr.io/$(imageName)
  displayName: 'docker push'

#- task: Docker@2
#  displayName: Login to ACR
#  inputs:
#    command: login
#    containerRegistry: aksclusterregistry01

#- task: Docker@2
#  inputs:
#    containerRegistry: aksclusterregistry01
#    repository: aksreisgtry01.azurecr.io/angularapp
#    command: buildAndPush
#    Dockerfile: Dockerfile
#    tags: $(Build.BuildId)

#- task: PublishBuildArtifacts@1
#  displayName: 'publish yaml folder as an artifact'
#  inputs:
#    artifactName: 'yaml' # this is the folder name where my artifact will store.
#    pathToPublish: 'manifest.yml' #file or folder needs to be publish in "yaml" folder (above step).
    #'yaml'
- task: PublishBuildArtifacts@1
  displayName: 'publish yaml folder as an artifact'
  inputs:
    artifactName: 'yaml' 
    pathToPublish: 'charts' 
 



#- publish: './application'
#  artifact: yaml-file


# link: https://sabbour.me/kubernetes-ci-cd-pipelines-using-azure-devops/
