apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: angular-webapp
  name: angular-webapp
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      app: angular-webapp
  strategy: 
   type: "{{ .Values.updatetype}}" 
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: angular-webapp
    spec:
      containers:
      - image: aksreisgtry01.azurecr.io/angularapp:"{{ .Values.image.tag}}"
     # ##BUILD_ID##
        name: webapp
        imagePullPolicy: Always
        resources: {}
        ports:
          - containerPort: 3080
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: angular-webapp
  labels:
    run: angular-webapp
spec:
  ports:
  - port: 3080
    protocol: TCP
  selector:
    app: angular-webapp
  type: LoadBalancer
